-- Payroll Workflow — pg_cron scheduling (OES AI Workforce, payroll pertama)
--
-- Sama seperti supabase/migrations/20260712010000_payroll_reminder_cron.sql —
-- di-comment out karena butuh 2 nilai yang cuma diketahui pas deploy:
--   1. URL production project ini (mis. https://xxxx.vercel.app)
--   2. Isi env PAYROLL_WORKFLOW_SECRET yang sama persis dengan yang di-set di server
--
-- Cara aktivasi (jalankan manual di Supabase SQL Editor):
--   1. Pastikan extension "pg_cron" & "pg_net" aktif (Database -> Extensions).
--   2. Copy blok SQL di bawah, ganti <PRODUCTION_URL> dan <PAYROLL_WORKFLOW_SECRET>.
--   3. Jalankan di SQL Editor.
--   4. Cek jadwal aktif: SELECT * FROM cron.job;
--   5. Cek histori run: SELECT * FROM cron.job_run_details ORDER BY start_time DESC LIMIT 10;
--
-- Jadwal: SETIAP HARI, 2x (10:00 & 18:00 UTC = 17:00 & 01:00 WIB) — HARUS
-- harian, bukan cuma Senin, karena periode gajian sekarang custom per client
-- (lihat migration 20260720000002_payroll_period_schedule.sql & Reminder
-- Calendar) — ada client yang periodenya tutup hari Kamis, ada yang Senin,
-- dst. Endpoint sendiri yang nentuin client mana yang periodenya jatuh tempo
-- hari itu (lihat src/lib/payroll-workflow.server.ts, resolvePeriodIfDue) —
-- kalau gak ada yang jatuh tempo, workflow tetap jalan tapi runs[] kosong
-- (bukan error). 2x sehari ngikutin jam cutoff data kiriman client (semua
-- kiriman hari itu udah pasti selesai jam 17:00 WIB) — dipake juga sama opsi
-- "Tutup di hari yang sama" di Reminder Calendar (close_same_day).
--
-- STATUS: SUDAH AKTIF di project ini (jobname 'payroll-workflow-daily',
-- cek: SELECT * FROM cron.job;). Blok di bawah cuma buat referensi/rebuild
-- kalau project di-reset atau dipindah — jangan re-run tanpa cek dulu apakah
-- job dengan nama sama udah ada (bakal error "already exists").

-- create extension if not exists pg_cron;
-- create extension if not exists pg_net;
--
-- select cron.schedule(
--   'payroll-workflow-daily',
--   '0 10,18 * * *', -- tiap hari jam 10:00 & 18:00 UTC (17:00 & 01:00 WIB)
--   $$
--   select net.http_post(
--     url := '<PRODUCTION_URL>/api/payroll-workflow',
--     headers := jsonb_build_object(
--       'Content-Type', 'application/json',
--       'x-payroll-workflow-secret', '<PAYROLL_WORKFLOW_SECRET>'
--     ),
--     body := '{"trigger": "scheduler"}'::jsonb
--   );
--   $$
-- );

-- Untuk ganti jadwal atau matikan cron:
--   select cron.unschedule('payroll-workflow-daily');
--   -- lalu jalankan ulang cron.schedule(...) di atas dengan jadwal baru.
